spring:
  application:
    name: tienda
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/tienda
    username: root
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
